import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Header from "@/components/ui/Header";
import { Comfortaa } from 'next/font/google'; // Importa la fuente

const comfortaa = Comfortaa({ weight: ['400', '700'], subsets: ['latin'] }); // Configura los pesos y subsets que necesitas

export const metadata: Metadata = {
  title: "buche",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Providers>
          <Header></Header>
          {children}
        </Providers>
        </body>
    </html>
  );
}

